### ISSUE TITLE
Might be a non issue but google maps api key in code.

### ISSUE THREAD

**Issue by rockBreaker** [Purple-Services/dashboard-cljs#26]
https://github.com/Purple-Services/dashboard-cljs/blob/d39698accbdf7c914e371f4dd9a213d0ebcf9bc4/resources/public/index.html#L18

As far as I understood you might not want to have this in your public repo as I _think_ you get billed based on usage? 

Apologies if i'm wrong.

**Comment by celwell** [comment]
Thanks, I appreciate the concern, I tried to redact any live API keys. I think that one is not connected to any account that can accrue charges; it was just for development.
